---
driver:
  # we cannot use the docker driver since we depend on systemd
  name: vagrant
  use_sudo: false

provisioner:
  name: ansible_playbook
  require_ansible_repo: true
  require_chef_omnibus: false
  hosts: host

platforms:
  - name: ubuntu-16.04
  - name: centos-7.2
  - name: debian-8

verifier:
  name: serverspec
  sudo_path: true

suites:
  - name: default
    run_list:
    attributes:
    verifier:
      default_pattern: true
      # see https://github.com/neillturner/kitchen-verifier-serverspec/issues/29
      additional_serverspec_command: 'if [ ! -f /tmp/verifier/suites ]; then mkdir -p /tmp/verifier/suites && ln -sf /tmp/verifier/serverspec /tmp/verifier/suites/serverspec; fi'
      bundler_path: /usr/local/bin
      rspec_path: /usr/local/bin